# Generated by Django 5.0.14 on 2026-06-17 11:43

from django.db import migrations


def seed_default_variants(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    Variant = apps.get_model('api', 'Variant')
    for product in Product.objects.all():
        if not product.variants.exists():
            Variant.objects.create(
                product=product,
                size_ml=100,
                price=product.price,
                stock=product.stock,
                sku=f"{product.slug}-100ml",
                is_active=True,
                sort_order=1,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactmessage_orderitem_variant_label_variant_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_variants, reverse_code=migrations.RunPython.noop),
    ]
