# Generated by Django 5.0.14 on 2026-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seed_default_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(help_text='Client-generated unique token', max_length=64, unique=True)),
                ('cart_data', models.JSONField(default=list, help_text='Array of cart items')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_72h_sent', models.BooleanField(default=False)),
                ('recovered', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(blank=True, help_text='Recovery coupon attached', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
